[build-system]
requires = [
    "setuptools>=42",
    "scikit-build",
    "cmake",
    "ninja",           # Optional, but faster builds
    "numpy"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel.linux]
before-build = """\
    dnf install -y python3-devel\n\
    pip install numpy scikit-build\n\
"""
